# Generated by Django 5.1.3 on 2024-12-16 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch_code', models.CharField(max_length=50, unique=True)),
                ('course', models.CharField(max_length=100)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('course_type', models.CharField(max_length=100)),
                ('ncs_unit', models.CharField(max_length=100)),
                ('max_students', models.PositiveIntegerField()),
                ('added_students', models.PositiveIntegerField(default=0)),
                ('lock_date', models.DateField()),
                ('students', models.ManyToManyField(blank=True, related_name='batches_as_student', to=settings.AUTH_USER_MODEL)),
                ('teachers', models.ManyToManyField(blank=True, related_name='batches_as_teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
