# Generated by Django 5.1.3 on 2024-12-16 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='course_type',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='name',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='ncs_unit',
        ),
        migrations.AlterField(
            model_name='batch',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='batch', to='courses.course'),
        ),
    ]
