# Generated by Django 5.1.3 on 2024-12-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_remove_batch_course_type_remove_batch_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
