# Generated by Django 5.1.4 on 2024-12-25 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='submission_deadline',
            new_name='deadline',
        ),
    ]
