# Generated by Django 5.1.4 on 2025-01-02 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentActivity',
            fields=[
                ('mainactivity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.mainactivity')),
                ('title', models.CharField(max_length=255)),
                ('difficulty_level', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('activities.mainactivity',),
        ),
        migrations.CreateModel(
            name='LearningActivity',
            fields=[
                ('mainactivity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.mainactivity')),
                ('title', models.CharField(max_length=255)),
                ('difficulty_level', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('activities.mainactivity',),
        ),
        migrations.RemoveField(
            model_name='question',
            name='exercise',
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Choice', 'verbose_name_plural': 'Choices'},
        ),
        migrations.AlterModelOptions(
            name='mainactivity',
            options={'ordering': ['-deadline']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'ordering': ['id'], 'verbose_name': 'Quiz Question', 'verbose_name_plural': 'Quiz Questions'},
        ),
        migrations.AlterModelOptions(
            name='quizsubmission',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Quiz Submission', 'verbose_name_plural': 'Quiz Submissions'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Submission', 'verbose_name_plural': 'Submissions'},
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='question',
            new_name='quiz_question',
        ),
        migrations.RemoveField(
            model_name='mainactivity',
            name='minutes',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='activity',
        ),
        migrations.AddField(
            model_name='mainactivity',
            name='duration_minutes',
            field=models.FloatField(default=1, help_text='Duration in minutes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mainactivity',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_main_activities', to='courses.activity'),
        ),
        migrations.AlterField(
            model_name='mainactivity',
            name='activity_code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='mainactivity',
            name='activity_type',
            field=models.CharField(choices=[('Exercise', 'Exercise'), ('Assignment', 'Assignment'), ('Project', 'Project'), ('Demonstration', 'Demonstration'), ('Lecture', 'Lecture'), ('Group', 'Group')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mainactivity',
            name='max_marks',
            field=models.FloatField(blank=True, help_text='Maximum marks for assessment activities', null=True),
        ),
        migrations.AlterField(
            model_name='mainactivity',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_main_activities', to='courses.session'),
        ),
        migrations.AlterField(
            model_name='question',
            name='weighting',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Weighting as a percentage (e.g., 25.00 for 25%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='weight',
            field=models.FloatField(default=1.0, help_text='Weight of the question towards the quiz score'),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='assessment_activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='activities.assessmentactivity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='learning_activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='activities.learningactivity'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
    ]
