# Generated by Django 5.1.4 on 2025-01-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_exercise_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markstracker',
            name='exercises_completed',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='markstracker',
            name='final_assessment_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='markstracker',
            name='final_grade',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='markstracker',
            name='industry_training_experience',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='markstracker',
            name='num_of_prev_attempts',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='markstracker',
            name='on_time_completion',
            field=models.BooleanField(verbose_name=False),
        ),
        migrations.AlterField(
            model_name='markstracker',
            name='practical_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='markstracker',
            name='tasks_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='markstracker',
            name='theory_hours',
            field=models.FloatField(default=0.0),
        ),
    ]
