# Generated by Django 5.1.4 on 2025-01-02 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_assessmentactivity_learningactivity_and_more'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainactivity',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_main_activities', to='courses.activity'),
        ),
        migrations.AlterField(
            model_name='mainactivity',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_main_activities', to='courses.session'),
        ),
    ]
