# Generated by Django 5.1.4 on 2025-01-07 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_alter_markstracker_exercises_completed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizsubmission',
            old_name='user',
            new_name='student',
        ),
    ]
