# Generated by Django 5.1.4 on 2025-01-02 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_alter_mainactivity_activity_and_more'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=255)),
                ('skill_score', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='assessment_activity',
        ),
        migrations.RemoveField(
            model_name='learningactivity',
            name='mainactivity_ptr',
        ),
        migrations.RemoveField(
            model_name='question',
            name='learning_activity',
        ),
        migrations.RemoveField(
            model_name='mainactivity',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='mainactivity',
            name='session',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='activity',
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={},
        ),
        migrations.AlterModelOptions(
            name='quizquestion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='quizsubmission',
            options={},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={},
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='quiz_question',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='activity_is_completed',
            new_name='exercise_is_completed',
        ),
        migrations.AddField(
            model_name='quiz',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.activity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Correct Answer'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Choice Text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='weighting',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='max_score',
            field=models.IntegerField(default=0, verbose_name='Total Score'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Quiz Title'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='text',
            field=models.TextField(verbose_name='Question Text'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='weight',
            field=models.FloatField(default=1.0, verbose_name='Weight (%)'),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.quiz'),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('difficulty_level', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=50)),
                ('max_score', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='courses.activity')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='exercise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='activities.exercise'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='exercise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='activities.exercise'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='skill',
            field=models.ManyToManyField(related_name='question_skills', to='activities.skill'),
        ),
        migrations.DeleteModel(
            name='AssessmentActivity',
        ),
        migrations.DeleteModel(
            name='LearningActivity',
        ),
        migrations.DeleteModel(
            name='MainActivity',
        ),
    ]
