# Generated by Django 5.1.4 on 2025-01-03 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_skill_remove_quiz_assessment_activity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='user',
            new_name='student',
        ),
    ]
