# Generated by Django 5.1.4 on 2025-01-06 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_questioncompletion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarksTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_marks', models.FloatField(default=0.0)),
                ('weekly_marks', models.FloatField(default=0.0)),
                ('monthly_marks', models.FloatField(default=0.0)),
                ('course_wise_marks', models.FloatField(default=0.0)),
                ('final_grade', models.CharField(max_length=10)),
                ('final_assessment_score', models.FloatField()),
                ('tasks_completed', models.IntegerField()),
                ('exercises_completed', models.IntegerField()),
                ('on_time_completion', models.BooleanField()),
                ('practical_hours', models.FloatField()),
                ('theory_hours', models.FloatField()),
                ('num_of_prev_attempts', models.IntegerField()),
                ('industry_training_experience', models.FloatField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
