# Generated by Django 5.1.4 on 2025-01-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_markstracker'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_code', models.CharField(max_length=10)),
                ('code_presentation', models.CharField(max_length=20)),
                ('id_student', models.IntegerField()),
                ('id_site', models.IntegerField()),
                ('date', models.IntegerField()),
                ('sum_click', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Student Activity Log',
                'verbose_name_plural': 'Student Activity Logs',
                'ordering': ['activity_code', 'code_presentation', 'id_student', 'date'],
            },
        ),
    ]
