# Generated by Django 5.1.4 on 2025-01-06 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_studentactivitylog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentactivitylog',
            options={'ordering': ['activity_code', 'exercise_code', 'id_student', 'date'], 'verbose_name': 'Student Activity Log', 'verbose_name_plural': 'Student Activity Logs'},
        ),
        migrations.RenameField(
            model_name='studentactivitylog',
            old_name='code_presentation',
            new_name='exercise_code',
        ),
    ]
