# Generated by Django 5.1.3 on 2024-12-24 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('certificate', models.ImageField(blank=True, null=True, upload_to='')),
                ('certificate_no', models.IntegerField(blank=True, null=True)),
                ('is_Certificate_issued', models.BooleanField(blank=True, null=True)),
                ('is_payment_completed', models.BooleanField(blank=True, null=True)),
                ('final_marks', models.IntegerField(blank=True, null=True)),
                ('module_marks', models.IntegerField(blank=True, null=True)),
                ('task_marks', models.IntegerField(blank=True, null=True)),
                ('completed_total_mod', models.IntegerField(blank=True, null=True)),
                ('completed_total_task', models.IntegerField(blank=True, null=True)),
                ('completed_total_activity', models.IntegerField(blank=True, null=True)),
                ('is_completed_total_tasks', models.BooleanField(blank=True, null=True)),
                ('industry_experiance', models.IntegerField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
