# Generated by Django 5.1.3 on 2024-12-24 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='certificate_no',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='completed_total_activity',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='completed_total_mod',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='completed_total_task',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='final_marks',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='github',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='industry_experiance',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_Certificate_issued',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_completed_total_tasks',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_payment_completed',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='module_marks',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='task_marks',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='twitter',
        ),
    ]
