# Generated by Django 5.1.4 on 2025-01-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='course_wise_marks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='daily_marks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='exercises_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='final_assessment_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='industry_training_experience',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='monthly_marks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='num_of_prev_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='on_time_completion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='practical_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='tasks_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='theory_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='weekly_marks',
            field=models.FloatField(default=0.0),
        ),
    ]
