# Generated by Django 5.1.4 on 2025-01-06 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('activities', '0002_alter_exercise_slug'),
        ('courses', '0002_alter_activity_slug_alter_course_course_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clicklog',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='click_log_activity', to='courses.activity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clicklog',
            name='exercise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='click_log_execise', to='activities.exercise'),
            preserve_default=False,
        ),
    ]
