# Generated by Django 5.1.4 on 2025-01-06 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_clicklog_activity_clicklog_exercise'),
        ('activities', '0002_alter_exercise_slug'),
        ('courses', '0002_alter_activity_slug_alter_course_course_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clicklog',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='click_log_activity', to='courses.activity'),
        ),
        migrations.AlterField(
            model_name='clicklog',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='click_log_exercise', to='activities.exercise'),
        ),
        migrations.AddIndex(
            model_name='clicklog',
            index=models.Index(fields=['timestamp'], name='accounts_cl_timesta_616510_idx'),
        ),
        migrations.AddIndex(
            model_name='clicklog',
            index=models.Index(fields=['activity'], name='accounts_cl_activit_fced84_idx'),
        ),
    ]
