# Generated by Django 5.1.4 on 2024-12-28 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200, unique=True)),
                ('course_code', models.CharField(max_length=50, unique=True)),
                ('entry_qualification', models.CharField(max_length=200)),
                ('medium', models.CharField(choices=[('sinhala_lng', 'SINHALA'), ('english_lng', 'ENGLISH')], max_length=100)),
                ('course_duration_months', models.PositiveIntegerField()),
                ('delivery_mode', models.CharField(choices=[('classroom', 'Classroom'), ('online', 'Online'), ('blended', 'Blended (both classroom & online)')], max_length=50)),
                ('course_mode', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time')], max_length=50)),
                ('curriculum_availability', models.BooleanField(default=True)),
                ('no_of_batches_per_year', models.PositiveIntegerField()),
                ('max_students_per_batch', models.PositiveIntegerField()),
                ('course_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('course_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theory_hrs', models.PositiveIntegerField()),
                ('practical_hrs', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_code', models.CharField(max_length=3, unique=True)),
                ('session_type', models.CharField(choices=[('Knowledge-Based', 'Knowledge-Based'), ('Hands-On', 'Hands-On'), ('Integrated', 'Integrated')], help_text='Knowledge-Based: Theoretical, Hands-On: Practical, Integrated: Both Theoretical and Practical', max_length=50)),
                ('session_minutes', models.PositiveIntegerField(verbose_name='Session Duration (Minutes)')),
                ('session_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Session Cost')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=200)),
                ('module_code', models.CharField(max_length=200)),
                ('theory_hours', models.PositiveIntegerField()),
                ('practical_hours', models.PositiveIntegerField()),
                ('module_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module_duration_weeks', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('task_code', models.CharField(max_length=10)),
                ('theory_hours', models.PositiveIntegerField()),
                ('practical_hours', models.PositiveIntegerField()),
                ('task_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_duration_days', models.PositiveIntegerField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='courses.module')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=200)),
                ('activity_code', models.CharField(max_length=10, unique=True, verbose_name='Activity Code')),
                ('activity_type', models.CharField(choices=[('Technical Knowledge', 'Technical Knowledge'), ('Skill Development', 'Skill Development'), ('Workplace Readiness', 'Workplace Readiness'), ('Assessment', 'Assessment'), ('Problem-Solving', 'Problem-Solving'), ('Industry-Specific', 'Industry-Specific'), ('Creative and Design', 'Creative and Design'), ('Self-Learning', 'Self-Learning'), ('Collaborative', 'Collaborative'), ('Reflective and Feedback', 'Reflective and Feedback')], max_length=50)),
                ('activity_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Activity Cost')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('no_of_sessions', models.PositiveIntegerField(default=1, verbose_name='Number of Sessions')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='courses.session')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_activities', to='courses.task')),
            ],
        ),
    ]
