# Generated by Django 5.1.4 on 2024-12-25 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='module_duration_days',
            new_name='task_duration_days',
        ),
    ]
