# Generated by Django 5.1.4 on 2024-12-25 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_module_duration_days_task_task_duration_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('Knowledge-Based', 'Knowledge-Based'), ('Hands-On', 'Hands-On'), ('Integrated', 'Integrated')], max_length=50)),
                ('session_minutes', models.PositiveIntegerField(verbose_name='Session Duration (Minutes)')),
                ('session_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Session Cost')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=200)),
                ('activity_code', models.CharField(max_length=10, unique=True, verbose_name='Activity Code')),
                ('activity_type', models.CharField(choices=[('Technical Knowledge', 'Technical Knowledge'), ('Skill Development', 'Skill Development'), ('Workplace Readiness', 'Workplace Readiness'), ('Assessment', 'Assessment'), ('Problem-Solving', 'Problem-Solving'), ('Industry-Specific', 'Industry-Specific'), ('Creative and Design', 'Creative and Design'), ('Self-Learning', 'Self-Learning'), ('Collaborative', 'Collaborative'), ('Reflective and Feedback', 'Reflective and Feedback')], max_length=50)),
                ('activity_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Activity Cost')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('no_of_sessions', models.PositiveIntegerField(default=1, verbose_name='Number of Sessions')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_activities', to='courses.task')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='courses.session')),
            ],
        ),
    ]
