# Generated by Django 5.1.4 on 2024-12-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_session_session_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Session Cost'),
        ),
    ]
