# Generated by Django 5.1.3 on 2024-12-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_name', models.CharField(help_text='Name of the training center.', max_length=200)),
                ('address', models.TextField(help_text='Address of the training center.')),
                ('contact_number', models.CharField(blank=True, help_text='Contact number of the training center.', max_length=15, null=True)),
                ('email', models.EmailField(blank=True, help_text='Email address of the training center.', max_length=254, null=True)),
                ('registration_number', models.CharField(help_text='Unique registration number of the training center.', max_length=50, unique=True)),
                ('established_date', models.DateField(blank=True, help_text='Date when the training center was established.', null=True)),
                ('head_of_center', models.CharField(blank=True, help_text='Name of the head of the training center.', max_length=100, null=True)),
                ('total_capacity', models.PositiveIntegerField(blank=True, help_text='Total capacity of trainees the center can accommodate.', null=True)),
                ('specialization', models.CharField(blank=True, help_text='Specialization or focus area of the training center.', max_length=200, null=True)),
            ],
        ),
    ]
