# Generated by Django 5.1.4 on 2024-12-28 12:03

import center.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_name', models.CharField(help_text='Name of the training center.', max_length=200, verbose_name='Training Center Name')),
                ('address', models.TextField(help_text='Address of the training center.', verbose_name='Address')),
                ('contact_number', models.CharField(blank=True, help_text='Contact number of the training center.', max_length=15, null=True, verbose_name='Contact Number')),
                ('email', models.EmailField(blank=True, help_text='Email address of the training center.', max_length=254, null=True, verbose_name='Email Address')),
                ('registration_number', models.CharField(help_text='Unique registration number of the training center.', max_length=50, unique=True, verbose_name='Registration Number')),
                ('established_date', models.DateField(blank=True, help_text='Date when the training center was established.', null=True, verbose_name='Established Date')),
                ('head_of_center', models.CharField(blank=True, help_text='Name of the head of the training center.', max_length=100, null=True, verbose_name='Head of Center')),
                ('total_capacity', models.PositiveIntegerField(blank=True, help_text='Total capacity of trainees the center can accommodate.', null=True, verbose_name='Total Capacity')),
                ('specialization', models.CharField(blank=True, help_text='Specialization or focus area of the training center.', max_length=200, null=True, verbose_name='Specialization')),
                ('contact_person', models.CharField(blank=True, help_text='Contact person for inquiries.', max_length=200, null=True, verbose_name='Contact Person')),
                ('business_reg_no', models.CharField(blank=True, help_text='Business Registration Number.', max_length=50, null=True, verbose_name='Business Registration Number')),
                ('business_reg_copy', models.FileField(blank=True, help_text='Upload the business registration copy as a PDF file.', null=True, upload_to='br/', validators=[center.models.validate_pdf_extension], verbose_name='Business Registration Copy (PDF)')),
                ('tvec_reg_copy', models.FileField(blank=True, help_text='Upload the TVEC registration copy  a PDF file.', null=True, upload_to='br/', validators=[center.models.validate_pdf_extension], verbose_name='TVEC Registration Copy  (PDF)')),
            ],
        ),
    ]
