# Generated by Django 5.1.4 on 2024-12-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcenter',
            name='br_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trainingcenter',
            name='contact_person',
            field=models.CharField(blank=True, help_text='Person who need contact', max_length=200, null=True),
        ),
    ]
