# Generated by Django 5.1.4 on 2024-12-25 14:43

import center.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0003_remove_trainingcenter_br_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingcenter',
            name='address',
            field=models.TextField(help_text='Address of the training center.', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='trainingcenter',
            name='business_reg_copy',
            field=models.FileField(blank=True, help_text='Upload the business registration copy as a PDF file.', null=True, upload_to='br/', validators=[center.models.validate_pdf_extension], verbose_name='Business Registration Copy (PDF)'),
        ),
        migrations.AlterField(
            model_name='trainingcenter',
            name='business_reg_no',
            field=models.CharField(blank=True, help_text='Business Registration Number.', max_length=50, null=True, verbose_name='Business Registration Number'),
        ),
        migrations.AlterField(
            model_name='trainingcenter',
            name='center_name',
            field=models.CharField(help_text='Name of the training center.', max_length=200, verbose_name='Training Center Name'),
        ),
        migrations.AlterField(
            model_name='trainingcenter',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Contact number of the training center.', max_length=15, null=True, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='trainingcenter',
            name='contact_person',
            field=models.CharField(blank=True, help_text='Contact person for inquiries.', max_length=200, null=True, verbose_name='Contact Person'),
        ),
        migrations.AlterField(
            model_name='trainingcenter',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address of the training center.', max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='trainingcenter',
            name='established_date',
            field=models.DateField(blank=True, help_text='Date when the training center was established.', null=True, verbose_name='Established Date'),
        ),
        migrations.AlterField(
            model_name='trainingcenter',
            name='head_of_center',
            field=models.CharField(blank=True, help_text='Name of the head of the training center.', max_length=100, null=True, verbose_name='Head of Center'),
        ),
        migrations.AlterField(
            model_name='trainingcenter',
            name='registration_number',
            field=models.CharField(help_text='Unique registration number of the training center.', max_length=50, unique=True, verbose_name='Registration Number'),
        ),
        migrations.AlterField(
            model_name='trainingcenter',
            name='specialization',
            field=models.CharField(blank=True, help_text='Specialization or focus area of the training center.', max_length=200, null=True, verbose_name='Specialization'),
        ),
        migrations.AlterField(
            model_name='trainingcenter',
            name='total_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Total capacity of trainees the center can accommodate.', null=True, verbose_name='Total Capacity'),
        ),
        migrations.AlterField(
            model_name='trainingcenter',
            name='tvec_reg_copy',
            field=models.FileField(blank=True, help_text='Upload the TVEC registration copy  a PDF file.', null=True, upload_to='br/', validators=[center.models.validate_pdf_extension], verbose_name='TVEC Registration Copy  (PDF)'),
        ),
    ]
