# Generated by Django 5.1.4 on 2025-01-06 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('center', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prepared', models.DateField()),
                ('trade_subject', models.CharField(max_length=200)),
                ('occupation', models.CharField(max_length=200)),
                ('date_revised', models.DateField(blank=True, null=True)),
                ('coordinator_name', models.CharField(max_length=100)),
                ('total_duration', models.PositiveIntegerField(help_text='Total duration of the course in hours')),
                ('commencement_date', models.DateField()),
                ('completion_date', models.DateField()),
                ('overview', models.TextField(help_text='General overview or objectives of the course')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_plan', to='courses.course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CoursePlanModules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('course_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='schedules.courseplan')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_modules', to='courses.module')),
            ],
        ),
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prepared', models.DateField()),
                ('trade_subject', models.CharField(max_length=200)),
                ('occupation', models.CharField(max_length=200)),
                ('date_revised', models.DateField(blank=True, null=True)),
                ('expected_date_commencement', models.DateField()),
                ('actual_date_commencement', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('machinery_tools', models.TextField(help_text='List of machinery, tools, and equipment required')),
                ('instructional_material', models.TextField(help_text='List of instructional materials required')),
                ('special_remarks', models.TextField(blank=True, null=True)),
                ('topic_subject', models.CharField(max_length=200)),
                ('total_duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('learning_objectives', models.TextField(help_text='Learning objectives for the session')),
                ('teaching_activities', models.TextField(help_text="Trainer's activities during the session")),
                ('learner_activities', models.TextField(help_text="Learner's activities during the session")),
                ('resources_visuals', models.TextField(help_text='Resources and visuals required')),
                ('assessment_activities', models.TextField()),
                ('conclusion', models.TextField()),
                ('trainer_signature', models.CharField(max_length=200)),
                ('course_plan_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='schedules.courseplanmodules')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_modules', to='courses.module')),
                ('resources', models.ManyToManyField(related_name='lesson_resources', to='center.resource')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_tasks', to='courses.task')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prepared', models.DateField()),
                ('trade_subject', models.CharField(max_length=200)),
                ('occupation', models.CharField(max_length=200)),
                ('date_revised', models.DateField(blank=True, null=True)),
                ('training_plan_title', models.TextField(help_text='Details of the sessions in the plan')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='training_plan', to='courses.course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrainingPlanModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_modules', to='courses.module')),
                ('training_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='schedules.trainingplan')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingPlanTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_tasks', to='courses.task')),
                ('training_plan_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='schedules.trainingplanmodule')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prepared', models.DateField()),
                ('trade_subject', models.CharField(max_length=200)),
                ('occupation', models.CharField(max_length=200)),
                ('date_revised', models.DateField(blank=True, null=True)),
                ('course_plan_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_plans', to='schedules.courseplanmodules')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_plan_modules', to='courses.module')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeeklyTaskPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_tasks', to='courses.task')),
                ('weekly_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='schedules.weeklyplan')),
            ],
        ),
    ]
