# Generated by Django 5.1.4 on 2024-12-25 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0005_alter_session_session_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('start_date', models.DateField(help_text='Start date of the plan.')),
                ('end_date', models.DateField(help_text='End date of the plan.')),
                ('no_weeks', models.PositiveIntegerField(help_text='Number of weeks in the plan.')),
                ('no_days', models.PositiveIntegerField(help_text='Number of days in the plan.')),
                ('no_sessions', models.PositiveIntegerField(help_text='Number of sessions in the plan.')),
                ('no_theory_hrs', models.PositiveIntegerField(help_text='Number of theory hours in the plan.')),
                ('no_practical_hrs', models.PositiveIntegerField(help_text='Number of practical hours in the plan.')),
            ],
        ),
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('mainplan_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedules.mainplan')),
                ('no_minutes', models.PositiveIntegerField(help_text='Number of minutes allocated for the lesson.')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_plan', to='courses.activity')),
            ],
            bases=('schedules.mainplan',),
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('mainplan_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedules.mainplan')),
                ('no_months', models.PositiveIntegerField(help_text='Number of months for the training plan.')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules_plan', to='courses.module')),
            ],
            bases=('schedules.mainplan',),
        ),
        migrations.CreateModel(
            name='CoursePlan',
            fields=[
                ('mainplan_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedules.mainplan')),
                ('no_months', models.PositiveIntegerField(help_text='Number of months for the course plan.')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_plan', to='courses.course')),
                ('training_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_plan', to='schedules.trainingplan')),
            ],
            bases=('schedules.mainplan',),
        ),
        migrations.CreateModel(
            name='WeeklyPlan',
            fields=[
                ('mainplan_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedules.mainplan')),
                ('total_hours', models.PositiveIntegerField(help_text='Total hours allocated for the week.')),
                ('total_minutes', models.PositiveIntegerField(help_text='Total minutes allocated for the week.')),
                ('lesson_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_paln', to='schedules.lessonplan')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_paln', to='courses.task')),
            ],
            bases=('schedules.mainplan',),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='weekly_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_plan', to='schedules.weeklyplan'),
        ),
    ]
