# Generated by Django 5.1.4 on 2024-12-28 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_centre', models.CharField(max_length=200)),
                ('trainer_name', models.CharField(max_length=100)),
                ('date_prepared', models.DateField()),
                ('resources_required', models.TextField(help_text='Consumables, tools, and equipment needed')),
                ('assessment_methods', models.TextField(help_text='Details about assessments during the plan')),
                ('coordinator_name', models.CharField(max_length=100)),
                ('total_duration', models.PositiveIntegerField(help_text='Total duration of the course in hours')),
                ('commencement_date', models.DateField()),
                ('completion_date', models.DateField()),
                ('overview', models.TextField(help_text='General overview or objectives of the course')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_plan', to='courses.course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_centre', models.CharField(max_length=200)),
                ('trainer_name', models.CharField(max_length=100)),
                ('date_prepared', models.DateField()),
                ('resources_required', models.TextField(help_text='Consumables, tools, and equipment needed')),
                ('assessment_methods', models.TextField(help_text='Details about assessments during the plan')),
                ('trade_subject', models.CharField(max_length=200)),
                ('expected_date_commencement', models.DateField()),
                ('actual_date_commencement', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('machinery_tools', models.TextField(help_text='List of machinery, tools, and equipment required')),
                ('instructional_material', models.TextField(help_text='List of instructional materials required')),
                ('special_remarks', models.TextField(blank=True, null=True)),
                ('topic_subject', models.CharField(max_length=200)),
                ('total_duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('learning_objectives', models.TextField(help_text='Learning objectives for the session')),
                ('teaching_activities', models.TextField(help_text="Trainer's activities during the session")),
                ('learner_activities', models.TextField(help_text="Learner's activities during the session")),
                ('resources_visuals', models.TextField(help_text='Resources and visuals required')),
                ('assessment_activities', models.TextField()),
                ('conclusion', models.TextField()),
                ('trainer_signature', models.CharField(max_length=200)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='courses.module')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='courses.task')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_centre', models.CharField(max_length=200)),
                ('trainer_name', models.CharField(max_length=100)),
                ('date_prepared', models.DateField()),
                ('resources_required', models.TextField(help_text='Consumables, tools, and equipment needed')),
                ('assessment_methods', models.TextField(help_text='Details about assessments during the plan')),
                ('occupation', models.CharField(max_length=200)),
                ('date_revised', models.DateField(blank=True, null=True)),
                ('week_number', models.PositiveIntegerField()),
                ('session_info', models.TextField(help_text='Details of the sessions in the plan')),
                ('tasks_to_cover', models.TextField()),
                ('special_services', models.TextField(blank=True, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_plans', to='courses.module')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeeklyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_centre', models.CharField(max_length=200)),
                ('trainer_name', models.CharField(max_length=100)),
                ('date_prepared', models.DateField()),
                ('resources_required', models.TextField(help_text='Consumables, tools, and equipment needed')),
                ('assessment_methods', models.TextField(help_text='Details about assessments during the plan')),
                ('week_number', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('tasks_to_cover', models.TextField(help_text='List of tasks or objectives for the week')),
                ('activities', models.TextField(help_text='Details about activities to be conducted during the week')),
                ('assessment_schedule', models.TextField(help_text='Planned assessments for the week')),
                ('course_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_plans', to='schedules.courseplan')),
                ('modules_covered', models.ManyToManyField(related_name='weekly_plans', to='courses.module')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
