# Generated by Django 5.1.4 on 2025-01-10 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseplan',
            name='course',
        ),
        migrations.AddField(
            model_name='courseplan',
            name='batch',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_plan', to='enrollments.batch'),
            preserve_default=False,
        ),
    ]
