# Generated by Django 5.1.4 on 2024-12-25 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseplan',
            name='training_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings_plan', to='schedules.trainingplan'),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='weekly_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeklys_plan', to='schedules.weeklyplan'),
        ),
        migrations.AlterField(
            model_name='weeklyplan',
            name='lesson_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons_paln', to='schedules.lessonplan'),
        ),
    ]
