# Generated by Django 5.1.4 on 2024-12-28 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseplan',
            name='assessment_methods',
        ),
        migrations.RemoveField(
            model_name='courseplan',
            name='resources_required',
        ),
        migrations.RemoveField(
            model_name='courseplan',
            name='trainer_name',
        ),
        migrations.RemoveField(
            model_name='courseplan',
            name='training_centre',
        ),
        migrations.RemoveField(
            model_name='lessonplan',
            name='assessment_methods',
        ),
        migrations.RemoveField(
            model_name='lessonplan',
            name='resources_required',
        ),
        migrations.RemoveField(
            model_name='lessonplan',
            name='trainer_name',
        ),
        migrations.RemoveField(
            model_name='lessonplan',
            name='training_centre',
        ),
        migrations.RemoveField(
            model_name='trainingplan',
            name='assessment_methods',
        ),
        migrations.RemoveField(
            model_name='trainingplan',
            name='resources_required',
        ),
        migrations.RemoveField(
            model_name='trainingplan',
            name='trainer_name',
        ),
        migrations.RemoveField(
            model_name='trainingplan',
            name='training_centre',
        ),
        migrations.RemoveField(
            model_name='weeklyplan',
            name='assessment_methods',
        ),
        migrations.RemoveField(
            model_name='weeklyplan',
            name='resources_required',
        ),
        migrations.RemoveField(
            model_name='weeklyplan',
            name='trainer_name',
        ),
        migrations.RemoveField(
            model_name='weeklyplan',
            name='training_centre',
        ),
    ]
