# Generated by Django 5.1.4 on 2025-01-10 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
        ('schedules', '0002_remove_courseplan_course_courseplan_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseplan',
            name='batch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='batch_plan', to='enrollments.batch'),
        ),
    ]
