# Generated by Django 5.1.4 on 2024-12-28 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('schedules', '0002_remove_courseplan_assessment_methods_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans_module', to='courses.module'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans_task', to='courses.task'),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_plans_module', to='courses.module'),
        ),
        migrations.AlterField(
            model_name='weeklyplan',
            name='course_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_plans_course_plan', to='schedules.courseplan'),
        ),
        migrations.AlterField(
            model_name='weeklyplan',
            name='modules_covered',
            field=models.ManyToManyField(related_name='weekly_plans_modules', to='courses.module'),
        ),
    ]
