# Generated by Django 5.1.4 on 2024-12-28 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_resource'),
        ('schedules', '0003_alter_lessonplan_module_alter_lessonplan_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingplan',
            name='resources',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='training_plans_resources', to='center.resource'),
            preserve_default=False,
        ),
    ]
