# Generated by Django 5.1.4 on 2024-12-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_resource'),
        ('schedules', '0004_trainingplan_resources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingplan',
            name='resources',
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='resources',
            field=models.ManyToManyField(related_name='training_plans_resources', to='center.resource'),
        ),
    ]
