# Generated by Django 5.1.4 on 2024-12-28 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_remove_trainingplan_resources_lessonplan_resources'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePlanModules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('course_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_plan_moduels', to='schedules.courseplan')),
            ],
        ),
    ]
