# Generated by Django 5.1.4 on 2024-12-28 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('schedules', '0007_courseplanmodules_module'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingplan',
            old_name='session_info',
            new_name='training_plan_title',
        ),
        migrations.RemoveField(
            model_name='trainingplan',
            name='module',
        ),
        migrations.RemoveField(
            model_name='trainingplan',
            name='tasks_to_cover',
        ),
        migrations.RemoveField(
            model_name='trainingplan',
            name='week_number',
        ),
        migrations.AddField(
            model_name='courseplan',
            name='date_revised',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseplan',
            name='occupation',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='date_revised',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='occupation',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='date_revised',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='occupation',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TrainingPlanModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_plans_module_module', to='courses.module')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_plans_module_task', to='courses.task')),
                ('training_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_plans_module_training_plan', to='schedules.trainingplan')),
            ],
        ),
    ]
