# Generated by Django 5.1.4 on 2024-12-28 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_resource'),
        ('courses', '0001_initial'),
        ('schedules', '0008_rename_session_info_trainingplan_training_plan_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingplan',
            name='special_services',
        ),
        migrations.RemoveField(
            model_name='trainingplanmodule',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='trainingplanmodule',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='trainingplanmodule',
            name='task',
        ),
        migrations.RemoveField(
            model_name='weeklyplan',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='weeklyplan',
            name='assessment_schedule',
        ),
        migrations.RemoveField(
            model_name='weeklyplan',
            name='course_plan',
        ),
        migrations.RemoveField(
            model_name='weeklyplan',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='weeklyplan',
            name='modules_covered',
        ),
        migrations.RemoveField(
            model_name='weeklyplan',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='weeklyplan',
            name='tasks_to_cover',
        ),
        migrations.RemoveField(
            model_name='weeklyplan',
            name='week_number',
        ),
        migrations.AddField(
            model_name='courseplan',
            name='trade_subject',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='course_plan_module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='schedules.courseplanmodules'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='course',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='training_plan', to='courses.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='trade_subject',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='course_plan_module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_plans', to='schedules.courseplanmodules'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_plan_modules', to='courses.module'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='trade_subject',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courseplanmodules',
            name='course_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='schedules.courseplan'),
        ),
        migrations.AlterField(
            model_name='courseplanmodules',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_modules', to='courses.module'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_modules', to='courses.module'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='resources',
            field=models.ManyToManyField(related_name='lesson_resources', to='center.resource'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_tasks', to='courses.task'),
        ),
        migrations.AlterField(
            model_name='trainingplanmodule',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_modules', to='courses.module'),
        ),
        migrations.AlterField(
            model_name='trainingplanmodule',
            name='training_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='schedules.trainingplan'),
        ),
        migrations.CreateModel(
            name='TrainingPlanTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_tasks', to='courses.task')),
                ('training_plan_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='schedules.trainingplanmodule')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyTaskPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_tasks', to='courses.task')),
                ('weekly_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='schedules.weeklyplan')),
            ],
        ),
    ]
